import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuHeader from "./components/organisms/Banner/MenuHeader";
import "./globals.css";
import RecoilRootWrapper from "./components/atoms/RecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuHeader />
        <RecoilRootWrapper>{children}</RecoilRootWrapper>
      </body>
    </html>
  );
}
